In [1]:
import numpy as np 
import matplotlib.pyplot as plt  
import random
random.seed(0) 

def load_data_from_file(filename = r"C:\Users\HOME\OneDrive\Documents\Downloads\advertising.csv"):
    data = np.genfromtxt(filename, dtype=None, delimiter=',', skip_header=1)

    features_X = data[:, :3]  
    sales_Y = data[:, 3]      

    ones_column = np.ones((features_X.shape[0], 1)) 
    features_X = np.hstack((ones_column, features_X))  

    return features_X, sales_Y

# Ví dụ sử dụng:
features_X, sales_Y = load_data_from_file()
print(features_X)  # In dữ liệu features_X (có thêm cột 1 ở đầu)
print(sales_Y)     # In dữ liệu sales_Y (output)


[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]
 [  1.    8.7  48.9  75. ]
 [  1.   57.5  32.8  23.5]
 [  1.  120.2  19.6  11.6]
 [  1.    8.6   2.1   1. ]
 [  1.  199.8   2.6  21.2]
 [  1.   66.1   5.8  24.2]
 [  1.  214.7  24.    4. ]
 [  1.   23.8  35.1  65.9]
 [  1.   97.5   7.6   7.2]
 [  1.  204.1  32.9  46. ]
 [  1.  195.4  47.7  52.9]
 [  1.   67.8  36.6 114. ]
 [  1.  281.4  39.6  55.8]
 [  1.   69.2  20.5  18.3]
 [  1.  147.3  23.9  19.1]
 [  1.  218.4  27.7  53.4]
 [  1.  237.4   5.1  23.5]
 [  1.   13.2  15.9  49.6]
 [  1.  228.3  16.9  26.2]
 [  1.   62.3  12.6  18.3]
 [  1.  262.9   3.5  19.5]
 [  1.  142.9  29.3  12.6]
 [  1.  240.1  16.7  22.9]
 [  1.  248.8  27.1  22.9]
 [  1.   70.6  16.   40.8]
 [  1.  292.9  28.3  43.2]
 [  1.  112.9  17.4  38.6]
 [  1.   97.2   1.5  30. ]
 [  1.  265.6  20.    0.3]
 [  1.   95.7   1.4   7.4]
 [  1.  290.7   4.1   8.5]
 [  1.  266.9  43.8   5. ]
 

In [2]:
feature_X, _ = load_data_from_file()
print(feature_X[:5, :])




[[  1.  230.1  37.8  69.2]
 [  1.   44.5  39.3  45.1]
 [  1.   17.2  45.9  69.3]
 [  1.  151.5  41.3  58.5]
 [  1.  180.8  10.8  58.4]]


In [3]:
_, Sales_y = load_data_from_file()
print(Sales_y.shape)



(200,)


## Câu 2 ##

create random gene 

In [4]:
def create_individual(n = 4 , bound = 10):
    
    individual  = []
    for i in range(n):
        individual.append(random.uniform(-bound/2, +bound/2))
    
    return individual 

individual = create_individual()
print(individual)


[3.4442185152504816, 2.5795440294030243, -0.79428419169155, -2.4108324970703663]


## Câu 3 ##

build fitness function 


In [5]:
feature_X, Sales_y = load_data_from_file()
def compute_loss(individual):
    theta = np.array(individual)
    y_hat = feature_X.dot(theta)
    loss = np.multiply((y_hat - Sales_y), (y_hat - Sales_y)).mean()
    return loss 

def compute_fitness(individual):
    loss = compute_loss(individual)
    fitness_value = 1 / (loss + 1)
    return fitness_value
 
print("Kích thước của feature_X:", feature_X.shape)
print("Kích thước của individual:", len(individual))



Kích thước của feature_X: (200, 4)
Kích thước của individual: 4


In [6]:
features_X , sales_Y = load_data_from_file()
individual = [4.09 , 4.82 , 3.10 , 4.02]
fitness_score = compute_fitness (individual)
print(fitness_score )


1.0185991537088997e-06


## Câu 4 ##

crossover chromosome 


In [7]:
def crossover(individual1, individual2, crossover_rate = 0.5):
    individual1_new = individual1.copy()
    individual2_new = individual2.copy()

    for i in range(len(individual1)):
        if np.random.rand() <= crossover_rate:
            individual1_new[i], individual2_new[i] = individual2_new[i], individual1_new[i]

    return individual1_new, individual2_new






In [8]:
# question 5
individual1 = [4.09 , 4.82 , 3.10 , 4.02]
individual2 = [3.44 , 2.57 , -0.79 , -2.41]
individual1 , individual2 = crossover(individual1 , individual2 , 2.0)
print (" individual1 : " , individual1 )
print (" individual2 : " , individual2 )

 individual1 :  [3.44, 2.57, -0.79, -2.41]
 individual2 :  [4.09, 4.82, 3.1, 4.02]


## câu 5 ##

mutation chromosome 


In [9]:
import numpy as np

def mutate(individual, mutation_rate=0.05):
    individual_m = individual.copy()
    for i in range(len(individual_m)):
        if np.random.rand() <= mutation_rate:
            mutation_value = np.random.uniform(-0.5, 0.5) 
            individual_m[i] += mutation_value
    
    return individual_m

# Ví dụ sử dụng:
individual = [4.09, 4.82, 3.10, 4.02]
mutated_individual = mutate(individual)
print("Original Individual:", individual)
print("Mutated Individual:", mutated_individual)


Original Individual: [4.09, 4.82, 3.1, 4.02]
Mutated Individual: [4.09, 4.82, 3.1, 4.02]


In [10]:
before_individual = [4.09 , 4.82 , 3.10 , 4.02]
after_individual = mutate( individual , mutation_rate = 2.0)
print ( before_individual == after_individual )


False


## Câu 6 ##


In [11]:
def initialize_population(m):
    population = [create_individual() for _ in range(m)]
    return population



## Câu 7 ##


In [62]:
def selection(softed_old_population, m = 100):
    index1 = random.randint(1, m-1)
    while True:
        index2 = random.randint(1, m-1)
        if (index1 != index2):
            break
    
    individual_s = softed_old_population[index1]
    
    if(index2 > index1):
        individual_s = softed_old_population[index2]
    
    return individual_s